#!/usr/bin/with-contenv bash

export HOME=/config

if [ "${GT_ENABLED}" != "true" ]; then
    s6-svc -d .
    exit 0
fi

command="gt --ip 0.0.0.0 --port ${GT_PORT:-21000} --system-proxy false --silent"
command="$command${GT_VERBOSE+ --verbose \"green-tunnel:*\"}"
command="$command${GT_DNSTYPE+ --dns-type $GT_DNSTYPE}"
command="$command${GT_DNSSERVER+ --dns-server $GT_DNSSERVER}"

echo "*** executing => $command"
exec s6-setuidgid abc $command
