#!/usr/bin/with-contenv bash

if [ "${GT_ENABLED}" != "true" ] && [ "${PROXY_ENABLED}" != "true" ]; then
    echo "*** ERROR: No services available"
    exit 1
fi

# permissions
chown -R abc:abc \
    /config
