#!/usr/bin/with-contenv bash

if [ "${GT_ENABLED}" == "true" ]; then

    if [ "${GT_UPDATE}" == "true" ]; then
        echo "*** updating green-tunnel ..."
        npm i -g green-tunnel &> /dev/null
    fi

    echo "*** green-tunnel v$(gt --version) ready!"

fi
