#!/usr/bin/with-contenv bash

if [ "$(printenv GT_USE | tr -d '"' | tr -d "'")" == "true" ]; then

    # update green-tunnel silently
    npm i -g green-tunnel &> /dev/null

    # temporary fix for MODULE_NOT_FOUND error
    filename="/usr/lib/node_modules/green-tunnel/src/utils/analytics.js"
    [ -f "${filename}" ] && \
        sed -i "s/import uuid from 'uuid\/v4';/import { v4 as uuid } from 'uuid';/" \
            /usr/lib/node_modules/green-tunnel/src/utils/analytics.js

    echo "** green-tunnel v$(gt --version) ready!"

fi
