#!/usr/bin/with-contenv bash

if [ "$(printenv GT_ENABLED | tr -d '"' | tr -d "'")" == "true" ]; then

    if [ "$(printenv GT_UPDATE | tr -d '"' | tr -d "'")" == "true" ]; then
        echo "** updating green-tunnel ..."
        npm i -g green-tunnel &> /dev/null
    fi

    echo "** green-tunnel v$(gt --version) ready!"

fi
